### ISSUE TITLE
Design and Structure

### ISSUE THREAD

**Issue by mektrode** [Coders-Central/Coders-Central.github.io#3]
Someone come up with an idea or a wire frame of how they think website should look. then we can work from there....

**Comment by Solusin** [comment]
I'm a little concerned about our recent design, its a little to bright and simple, and to me unappealing, a more stantard sleek look would be fine with me.

**Comment by SindhujaD** [comment]
That's a good idea, but I think before we do that, if we decide what to make the webpage about/what to have in it, then it may be easier to make a design that would look good with it.

**Comment by mektrode** [comment]
Cool. So far im aware of a login and sign up section which means once the user is logged in the header bar will change to their username and any otver importsnt stuff like notifications.

Im also aware of some sort of chat system in the future is also planned.

What else am i missing?

And btw what is the user gonna log in for? Just for chat or is there other available features to them that would make them want to sign up?

**Comment by SindhujaD** [comment]
Idk, cause I have no idea what the website is gonna be about...

---

**Comment by Solusin** [comment]
We can make this like forums.

**Comment by SindhujaD** [comment]
That's a good idea, but can you look at my Issue named "Website Idea"cause it has an idea....

**Comment by mektrode** [comment]
Ok... so far i know that the website is about the following:-

=> Login / Sign up
=> Chat System
=> Forums

Anything else?
Something like tuts and articles about coding maybe?

**Comment by SindhujaD** [comment]
We could always do that, sounds like a good idea..

**Comment by Solusin** [comment]
Excellent, how about we do that.

**Comment by SindhujaD** [comment]
Sure, unless anyone has any objections...

**Comment by ABaker86** [comment]
The only issue that may come up is that a database will be needed in order to keep track of user credentials for logging/signing into the website. Perhaps a login feature could be added later. 

From what I have gathered from the CodeCademy discussion and this one is that a group of individuals are getting together to brush up on their coding skills. This leads me to believe that a Website based on the organization would contain content related and relevant to its members. 

I would suggest a sections of the Website could include the following: 
`Home Page`
`Members/Contributors Page` - Simple bio and image, possible links to their works 
`Current Projects` - current works that group is working on

Anything else should come later as the group grows.in population and knowledge.
